// Code generated by mockery v2.53.0. DO NOT EDIT.

package registry

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockModuleResolver is an autogenerated mock type for the ModuleResolver type
type MockModuleResolver struct {
	mock.Mock
}

// ParseModuleRegistrySource provides a mock function with given fields: ctx, moduleSource, tokenGetter, federatedRegistryGetter
func (_m *MockModuleResolver) ParseModuleRegistrySource(ctx context.Context, moduleSource string, tokenGetter TokenGetterFunc, federatedRegistryGetter FederatedRegistryGetterFunc) (ModuleRegistrySource, error) {
	ret := _m.Called(ctx, moduleSource, tokenGetter, federatedRegistryGetter)

	if len(ret) == 0 {
		panic("no return value specified for ParseModuleRegistrySource")
	}

	var r0 ModuleRegistrySource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, TokenGetterFunc, FederatedRegistryGetterFunc) (ModuleRegistrySource, error)); ok {
		return rf(ctx, moduleSource, tokenGetter, federatedRegistryGetter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, TokenGetterFunc, FederatedRegistryGetterFunc) ModuleRegistrySource); ok {
		r0 = rf(ctx, moduleSource, tokenGetter, federatedRegistryGetter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ModuleRegistrySource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, TokenGetterFunc, FederatedRegistryGetterFunc) error); ok {
		r1 = rf(ctx, moduleSource, tokenGetter, federatedRegistryGetter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockModuleResolver creates a new instance of MockModuleResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModuleResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModuleResolver {
	mock := &MockModuleResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
