// Code generated by mockery v2.53.0. DO NOT EDIT.

package email

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFeedbackProvider is an autogenerated mock type for the FeedbackProvider type
type MockFeedbackProvider struct {
	mock.Mock
}

// ConsumeFeedback provides a mock function with given fields: ctx, handle
func (_m *MockFeedbackProvider) ConsumeFeedback(ctx context.Context, handle FeedbackCallback) error {
	ret := _m.Called(ctx, handle)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, FeedbackCallback) error); ok {
		r0 = rf(ctx, handle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMail provides a mock function with given fields: ctx, to, subject, body, correlationID
func (_m *MockFeedbackProvider) SendMail(ctx context.Context, to string, subject string, body string, correlationID string) error {
	ret := _m.Called(ctx, to, subject, body, correlationID)

	if len(ret) == 0 {
		panic("no return value specified for SendMail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, to, subject, body, correlationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFeedbackProvider creates a new instance of MockFeedbackProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedbackProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedbackProvider {
	mock := &MockFeedbackProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
