// Code generated by mockery v2.53.0. DO NOT EDIT.

package logstream

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

// ReadRange provides a mock function with given fields: ctx, key, offset, length
func (_m *MockStore) ReadRange(ctx context.Context, key string, offset int, length int) (io.ReadCloser, error) {
	ret := _m.Called(ctx, key, offset, length)

	if len(ret) == 0 {
		panic("no return value specified for ReadRange")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (io.ReadCloser, error)); ok {
		return rf(ctx, key, offset, length)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) io.ReadCloser); ok {
		r0 = rf(ctx, key, offset, length)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, key, offset, length)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteChunk provides a mock function with given fields: ctx, key, byteOffset, buffer
func (_m *MockStore) WriteChunk(ctx context.Context, key string, byteOffset int, buffer []byte) error {
	ret := _m.Called(ctx, key, byteOffset, buffer)

	if len(ret) == 0 {
		panic("no return value specified for WriteChunk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, []byte) error); ok {
		r0 = rf(ctx, key, byteOffset, buffer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteObject provides a mock function with given fields: ctx, key, r
func (_m *MockStore) WriteObject(ctx context.Context, key string, r io.Reader) error {
	ret := _m.Called(ctx, key, r)

	if len(ret) == 0 {
		panic("no return value specified for WriteObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, key, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
