// Code generated by mockery v2.14.1. DO NOT EDIT.

package run

import (
	context "context"
	io "io"

	db "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/db"

	mock "github.com/stretchr/testify/mock"

	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// ApplyRun provides a mock function with given fields: ctx, runID, comment
func (_m *MockService) ApplyRun(ctx context.Context, runID string, comment *string) (*models.Run, error) {
	ret := _m.Called(ctx, runID, comment)

	var r0 *models.Run
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) *models.Run); ok {
		r0 = rf(ctx, runID, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Run)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = rf(ctx, runID, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelRun provides a mock function with given fields: ctx, options
func (_m *MockService) CancelRun(ctx context.Context, options *CancelRunInput) (*models.Run, error) {
	ret := _m.Called(ctx, options)

	var r0 *models.Run
	if rf, ok := ret.Get(0).(func(context.Context, *CancelRunInput) *models.Run); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Run)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *CancelRunInput) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimJob provides a mock function with given fields: ctx, runnerID
func (_m *MockService) ClaimJob(ctx context.Context, runnerID string) (*ClaimJobResponse, error) {
	ret := _m.Called(ctx, runnerID)

	var r0 *ClaimJobResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *ClaimJobResponse); ok {
		r0 = rf(ctx, runnerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ClaimJobResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, runnerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRun provides a mock function with given fields: ctx, options
func (_m *MockService) CreateRun(ctx context.Context, options *CreateRunInput) (*models.Run, error) {
	ret := _m.Called(ctx, options)

	var r0 *models.Run
	if rf, ok := ret.Get(0).(func(context.Context, *CreateRunInput) *models.Run); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Run)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *CreateRunInput) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DownloadPlan provides a mock function with given fields: ctx, planID
func (_m *MockService) DownloadPlan(ctx context.Context, planID string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, planID)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAppliesByIDs provides a mock function with given fields: ctx, idList
func (_m *MockService) GetAppliesByIDs(ctx context.Context, idList []string) ([]models.Apply, error) {
	ret := _m.Called(ctx, idList)

	var r0 []models.Apply
	if rf, ok := ret.Get(0).(func(context.Context, []string) []models.Apply); ok {
		r0 = rf(ctx, idList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Apply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, idList)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApply provides a mock function with given fields: ctx, applyID
func (_m *MockService) GetApply(ctx context.Context, applyID string) (*models.Apply, error) {
	ret := _m.Called(ctx, applyID)

	var r0 *models.Apply
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Apply); ok {
		r0 = rf(ctx, applyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Apply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, applyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestJobForApply provides a mock function with given fields: ctx, applyID
func (_m *MockService) GetLatestJobForApply(ctx context.Context, applyID string) (*models.Job, error) {
	ret := _m.Called(ctx, applyID)

	var r0 *models.Job
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Job); ok {
		r0 = rf(ctx, applyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, applyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestJobForPlan provides a mock function with given fields: ctx, planID
func (_m *MockService) GetLatestJobForPlan(ctx context.Context, planID string) (*models.Job, error) {
	ret := _m.Called(ctx, planID)

	var r0 *models.Job
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Job); ok {
		r0 = rf(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlan provides a mock function with given fields: ctx, planID
func (_m *MockService) GetPlan(ctx context.Context, planID string) (*models.Plan, error) {
	ret := _m.Called(ctx, planID)

	var r0 *models.Plan
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Plan); ok {
		r0 = rf(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlansByIDs provides a mock function with given fields: ctx, idList
func (_m *MockService) GetPlansByIDs(ctx context.Context, idList []string) ([]models.Plan, error) {
	ret := _m.Called(ctx, idList)

	var r0 []models.Plan
	if rf, ok := ret.Get(0).(func(context.Context, []string) []models.Plan); ok {
		r0 = rf(ctx, idList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, idList)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRun provides a mock function with given fields: ctx, runID
func (_m *MockService) GetRun(ctx context.Context, runID string) (*models.Run, error) {
	ret := _m.Called(ctx, runID)

	var r0 *models.Run
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Run); ok {
		r0 = rf(ctx, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Run)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, runID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunVariables provides a mock function with given fields: ctx, runID
func (_m *MockService) GetRunVariables(ctx context.Context, runID string) ([]Variable, error) {
	ret := _m.Called(ctx, runID)

	var r0 []Variable
	if rf, ok := ret.Get(0).(func(context.Context, string) []Variable); ok {
		r0 = rf(ctx, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Variable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, runID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRuns provides a mock function with given fields: ctx, input
func (_m *MockService) GetRuns(ctx context.Context, input *GetRunsInput) (*db.RunsResult, error) {
	ret := _m.Called(ctx, input)

	var r0 *db.RunsResult
	if rf, ok := ret.Get(0).(func(context.Context, *GetRunsInput) *db.RunsResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.RunsResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GetRunsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunsByIDs provides a mock function with given fields: ctx, idList
func (_m *MockService) GetRunsByIDs(ctx context.Context, idList []string) ([]models.Run, error) {
	ret := _m.Called(ctx, idList)

	var r0 []models.Run
	if rf, ok := ret.Get(0).(func(context.Context, []string) []models.Run); ok {
		r0 = rf(ctx, idList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Run)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, idList)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToRunEvents provides a mock function with given fields: ctx, options
func (_m *MockService) SubscribeToRunEvents(ctx context.Context, options *EventSubscriptionOptions) (<-chan *Event, error) {
	ret := _m.Called(ctx, options)

	var r0 <-chan *Event
	if rf, ok := ret.Get(0).(func(context.Context, *EventSubscriptionOptions) <-chan *Event); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *EventSubscriptionOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateApply provides a mock function with given fields: ctx, apply
func (_m *MockService) UpdateApply(ctx context.Context, apply *models.Apply) (*models.Apply, error) {
	ret := _m.Called(ctx, apply)

	var r0 *models.Apply
	if rf, ok := ret.Get(0).(func(context.Context, *models.Apply) *models.Apply); ok {
		r0 = rf(ctx, apply)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Apply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Apply) error); ok {
		r1 = rf(ctx, apply)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePlan provides a mock function with given fields: ctx, plan
func (_m *MockService) UpdatePlan(ctx context.Context, plan *models.Plan) (*models.Plan, error) {
	ret := _m.Called(ctx, plan)

	var r0 *models.Plan
	if rf, ok := ret.Get(0).(func(context.Context, *models.Plan) *models.Plan); ok {
		r0 = rf(ctx, plan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Plan) error); ok {
		r1 = rf(ctx, plan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadPlan provides a mock function with given fields: ctx, planID, reader
func (_m *MockService) UploadPlan(ctx context.Context, planID string, reader io.Reader) error {
	ret := _m.Called(ctx, planID, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, planID, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t mockConstructorTestingTNewMockService) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
