// Code generated by mockery v2.14.0. DO NOT EDIT.

package jwsprovider

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockJWSProvider is an autogenerated mock type for the JWSProvider type
type MockJWSProvider struct {
	mock.Mock
}

// GetKeySet provides a mock function with given fields: ctx
func (_m *MockJWSProvider) GetKeySet(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Sign provides a mock function with given fields: ctx, token
func (_m *MockJWSProvider) Sign(ctx context.Context, token []byte) ([]byte, error) {
	ret := _m.Called(ctx, token)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: ctx, token
func (_m *MockJWSProvider) Verify(ctx context.Context, token []byte) error {
	ret := _m.Called(ctx, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockJWSProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockJWSProvider creates a new instance of MockJWSProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockJWSProvider(t mockConstructorTestingTNewMockJWSProvider) *MockJWSProvider {
	mock := &MockJWSProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
