// Code generated by mockery v2.53.0. DO NOT EDIT.

package packageregistry

import (
	context "context"
	io "io"

	db "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/db"

	mock "github.com/stretchr/testify/mock"

	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockPackageStore is an autogenerated mock type for the PackageStore type
type MockPackageStore struct {
	mock.Mock
}

// DownloadPackageVersion provides a mock function with given fields: ctx, packageVersion, writer
func (_m *MockPackageStore) DownloadPackageVersion(ctx context.Context, packageVersion *models.PackageVersion, writer io.WriterAt) error {
	ret := _m.Called(ctx, packageVersion, writer)

	if len(ret) == 0 {
		panic("no return value specified for DownloadPackageVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion, io.WriterAt) error); ok {
		r0 = rf(ctx, packageVersion, writer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPackageVersionPresignedURL provides a mock function with given fields: ctx, packageVersion
func (_m *MockPackageStore) GetPackageVersionPresignedURL(ctx context.Context, packageVersion *models.PackageVersion) (string, error) {
	ret := _m.Called(ctx, packageVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageVersionPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion) (string, error)); ok {
		return rf(ctx, packageVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion) string); ok {
		r0 = rf(ctx, packageVersion)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.PackageVersion) error); ok {
		r1 = rf(ctx, packageVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadPackageVersion provides a mock function with given fields: ctx, packageVersion, body
func (_m *MockPackageStore) UploadPackageVersion(ctx context.Context, packageVersion *models.PackageVersion, body io.Reader) (db.RetainObjectRefFunc, string, error) {
	ret := _m.Called(ctx, packageVersion, body)

	if len(ret) == 0 {
		panic("no return value specified for UploadPackageVersion")
	}

	var r0 db.RetainObjectRefFunc
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion, io.Reader) (db.RetainObjectRefFunc, string, error)); ok {
		return rf(ctx, packageVersion, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion, io.Reader) db.RetainObjectRefFunc); ok {
		r0 = rf(ctx, packageVersion, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.RetainObjectRefFunc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.PackageVersion, io.Reader) string); ok {
		r1 = rf(ctx, packageVersion, body)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *models.PackageVersion, io.Reader) error); ok {
		r2 = rf(ctx, packageVersion, body)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockPackageStore creates a new instance of MockPackageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageStore {
	mock := &MockPackageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
