// Code generated by mockery v2.53.0. DO NOT EDIT.

package logstore

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

// GetEntries provides a mock function with given fields: levels, search, limit
func (_m *MockStore) GetEntries(levels []string, search string, limit int) ([]*LogEntry, error) {
	ret := _m.Called(levels, search, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetEntries")
	}

	var r0 []*LogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, string, int) ([]*LogEntry, error)); ok {
		return rf(levels, search, limit)
	}
	if rf, ok := ret.Get(0).(func([]string, string, int) []*LogEntry); ok {
		r0 = rf(levels, search, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*LogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string, int) error); ok {
		r1 = rf(levels, search, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: ctx
func (_m *MockStore) Subscribe(ctx context.Context) (<-chan *LogEntry, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan *LogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan *LogEntry, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan *LogEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *LogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: e
func (_m *MockStore) Write(e *LogEntry) {
	_m.Called(e)
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
