// Code generated by mockery v2.53.0. DO NOT EDIT.

package llm

import (
	context "context"

	gollem "github.com/m-mizutani/gollem"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// GenerateEmbedding provides a mock function with given fields: ctx, dimension, input
func (_m *MockClient) GenerateEmbedding(ctx context.Context, dimension int, input []string) ([][]float64, error) {
	ret := _m.Called(ctx, dimension, input)

	if len(ret) == 0 {
		panic("no return value specified for GenerateEmbedding")
	}

	var r0 [][]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []string) ([][]float64, error)); ok {
		return rf(ctx, dimension, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []string) [][]float64); ok {
		r0 = rf(ctx, dimension, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []string) error); ok {
		r1 = rf(ctx, dimension, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCreditCount provides a mock function with given fields: input
func (_m *MockClient) GetCreditCount(input CreditInput) float64 {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for GetCreditCount")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(CreditInput) float64); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// NewSession provides a mock function with given fields: ctx, options
func (_m *MockClient) NewSession(ctx context.Context, options ...gollem.SessionOption) (gollem.Session, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NewSession")
	}

	var r0 gollem.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...gollem.SessionOption) (gollem.Session, error)); ok {
		return rf(ctx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...gollem.SessionOption) gollem.Session); ok {
		r0 = rf(ctx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gollem.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...gollem.SessionOption) error); ok {
		r1 = rf(ctx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
