services:
  # Tharsis database.
  postgres:
    image: postgres:16-alpine
    container_name: tharsis-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tharsis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tharsis

  # Keycloak database
  kc_postgres:
    image: postgres:16-alpine
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - kc_postgres_data:/var/lib/postgresql/data
    networks:
      - tharsis

  # Identity provider.
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: tharsis-idp
    restart: unless-stopped
    command: "start-dev --db=postgres --db-url-host=keycloak-db --db-username=postgres --db-password=postgres --import-realm"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./tharsis-realm.json:/opt/keycloak/data/import/tharsis-realm.json:ro
    networks:
      - tharsis
    ports:
      - "127.0.0.1:6530:8080"
    depends_on:
      - kc_postgres

  tharsis:
    image: registry.gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/tharsis:latest
    container_name: tharsis
    restart: unless-stopped
    user: 0:0
    environment:
      - THARSIS_OAUTH_PROVIDERS_0_ISSUER_URL=http://localhost:6530/realms/tharsis
      - THARSIS_OAUTH_PROVIDERS_0_CLIENT_ID=tharsis
      - THARSIS_OAUTH_PROVIDERS_0_USERNAME_CLAIM=preferred_username
      - THARSIS_OAUTH_PROVIDERS_0_SCOPE=openid profile email
      - THARSIS_CLI_LOGIN_OIDC_SCOPES=openid tharsis
      - THARSIS_ADMIN_USER_EMAIL=martian@tharsis.local
      - THARSIS_DB_USERNAME=postgres
      - THARSIS_DB_NAME=tharsis
      - THARSIS_DB_PASSWORD=postgres
      - THARSIS_DB_HOST=postgres
      - THARSIS_DB_PORT=5432
      - THARSIS_DB_SSL_MODE=disable
      - THARSIS_OBJECT_STORE_PLUGIN_TYPE=filesystem
      - THARSIS_OBJECT_STORE_PLUGIN_DATA_DIRECTORY=/var/lib/tharsis
      - THARSIS_JWS_PROVIDER_PLUGIN_TYPE=memory
      - THARSIS_API_URL=http://localhost:6560
      - THARSIS_INTERNAL_RUNNERS_0_NAME=default-shared-runner
      - THARSIS_INTERNAL_RUNNERS_0_JOB_DISPATCHER_TYPE=docker
      - THARSIS_INTERNAL_RUNNERS_0_JOB_DISPATCHER_DATA_ENDPOINT=http://localhost:6560
      - THARSIS_INTERNAL_RUNNERS_0_JOB_DISPATCHER_DATA_HOST=unix:///var/run/docker.sock
      - THARSIS_INTERNAL_RUNNERS_0_JOB_DISPATCHER_DATA_EXTRA_HOSTS=localhost:host-gateway
      - THARSIS_INTERNAL_RUNNERS_0_JOB_DISPATCHER_DATA_IMAGE=registry.gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/job-executor:latest
      - THARSIS_INTERNAL_RUNNERS_0_JOB_DISPATCHER_DATA_LOCAL_IMAGE=false # Set to true if using local image.
      - THARSIS_ADMIN_LOG_TAIL_STORE_PLUGIN_TYPE=memory
      - THARSIS_OTEL_TRACE_ENABLED=true
      - THARSIS_OTEL_TRACE_TYPE=otlp
      - THARSIS_OTEL_TRACE_HOST=jaeger
      - THARSIS_OTEL_TRACE_PORT=4317
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Required for job-executor.
      - tharsis_objects:/var/lib/tharsis
    networks:
      - tharsis
    ports:
      - "127.0.0.1:6560:8000"
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      postgres:
        condition: service_started
      keycloak:
        condition: service_started

  jaeger:
    image: jaegertracing/all-in-one:1.44
    container_name: tharsis-jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - tharsis
    ports:
      - "127.0.0.1:16686:16686" # Jaeger UI
    expose:
      - "4317" # OTEL port

networks:
  tharsis:
    driver: bridge

volumes:
  postgres_data:
  kc_postgres_data:
  tharsis_objects:
