// Code generated by mockery v2.53.0. DO NOT EDIT.

package asynctask

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

// Shutdown provides a mock function with no fields
func (_m *MockManager) Shutdown() {
	_m.Called()
}

// StartTask provides a mock function with given fields: fn
func (_m *MockManager) StartTask(fn func(context.Context)) {
	_m.Called(fn)
}

// Timeout provides a mock function with no fields
func (_m *MockManager) Timeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Timeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
