// Code generated by mockery v2.14.0. DO NOT EDIT.

package eks

import (
	context "context"

	sts "github.com/aws/aws-sdk-go-v2/service/sts"
	mock "github.com/stretchr/testify/mock"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
)

// mockPresigner is an autogenerated mock type for the presigner type
type mockPresigner struct {
	mock.Mock
}

// PresignGetCallerIdentity provides a mock function with given fields: ctx, params, optFns
func (_m *mockPresigner) PresignGetCallerIdentity(ctx context.Context, params *sts.GetCallerIdentityInput, optFns ...func(*sts.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v4.PresignedHTTPRequest
	if rf, ok := ret.Get(0).(func(context.Context, *sts.GetCallerIdentityInput, ...func(*sts.PresignOptions)) *v4.PresignedHTTPRequest); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v4.PresignedHTTPRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sts.GetCallerIdentityInput, ...func(*sts.PresignOptions)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockPresigner interface {
	mock.TestingT
	Cleanup(func())
}

// newMockPresigner creates a new instance of mockPresigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockPresigner(t mockConstructorTestingTnewMockPresigner) *mockPresigner {
	mock := &mockPresigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
