// Code generated by mockery v2.53.0. DO NOT EDIT.

package registry

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
)

// mockRemoteClient is an autogenerated mock type for the remoteClient type
type mockRemoteClient struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *mockRemoteClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTerraformModuleAttestations provides a mock function with given fields: ctx, req
func (_m *mockRemoteClient) GetTerraformModuleAttestations(ctx context.Context, req *gen.GetTerraformModuleAttestationsRequest) (*gen.GetTerraformModuleAttestationsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModuleAttestations")
	}

	var r0 *gen.GetTerraformModuleAttestationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleAttestationsRequest) (*gen.GetTerraformModuleAttestationsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleAttestationsRequest) *gen.GetTerraformModuleAttestationsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetTerraformModuleAttestationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModuleAttestationsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformModuleVersionByID provides a mock function with given fields: ctx, req
func (_m *mockRemoteClient) GetTerraformModuleVersionByID(ctx context.Context, req *gen.GetTerraformModuleVersionByIDRequest) (*gen.TerraformModuleVersion, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModuleVersionByID")
	}

	var r0 *gen.TerraformModuleVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleVersionByIDRequest) (*gen.TerraformModuleVersion, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleVersionByIDRequest) *gen.TerraformModuleVersion); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModuleVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModuleVersionByIDRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockRemoteClient creates a new instance of mockRemoteClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRemoteClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRemoteClient {
	mock := &mockRemoteClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
