DROP TRIGGER jobs_notify_event ON jobs;
DROP TRIGGER runs_notify_event ON runs;
DROP TRIGGER workspaces_notify_event ON workspaces;
DROP TRIGGER runners_notify_event ON runners;
DROP TRIGGER maintenance_mode_notify_event on maintenance_mode;
DROP TRIGGER log_streams_notify_event on log_streams;
DROP TRIGGER runner_sessions_notify_event on runner_sessions;
DROP TRIGGER asym_signing_keys_notify_event on asym_signing_keys;

DROP FUNCTION notify_event;


ALTER TABLE workspaces DROP CONSTRAINT fk_current_job_id;
ALTER TABLE workspaces DROP CONSTRAINT fk_current_state_version_id;

DROP TABLE activity_events;
DROP TABLE service_account_runner_relation;
DROP TABLE terraform_module_attestations;
DROP TABLE terraform_module_versions;
DROP TABLE terraform_modules;
DROP TABLE workspace_vcs_provider_links;
DROP TABLE vcs_providers;
DROP TABLE scim_tokens;
DROP TABLE terraform_provider_platforms;
DROP TABLE terraform_provider_versions;
DROP TABLE terraform_providers;
DROP TABLE gpg_keys;
DROP TABLE workspace_managed_identity_relation;
DROP TABLE managed_identity_rule_allowed_users;
DROP TABLE managed_identity_rule_allowed_service_accounts;
DROP TABLE managed_identity_rule_allowed_teams;
DROP TABLE managed_identity_rules;
DROP TABLE managed_identities;
DROP TABLE team_members;
DROP TABLE state_version_outputs;
DROP TABLE state_versions;
DROP TABLE namespace_memberships;
DROP TABLE roles;
DROP TABLE teams;
DROP TABLE service_accounts;
DROP TABlE user_external_identities;
DROP TABLE log_streams;
DROP TABLE resource_limits;
DROP TABLE terraform_provider_platform_mirrors;
DROP TABLE terraform_provider_version_mirrors;
DROP TABLE maintenance_mode;
DROP TABLE runner_sessions;
DROP TABLE latest_namespace_variable_versions;
DROP TABLE namespace_variable_versions;
DROP TABLE namespace_variables;
DROP TABLE notification_preferences;
DROP TABLE namespaces;
DROP TABLE workspace_assessments;
DROP TABLE jobs;
DROP TABLE runners;
DROP TABLE runs;
DROP TABLE plans;
DROP TABLE applies;
DROP TABLE configuration_versions;
DROP TABLE vcs_events;
DROP TABLE federated_registries;
DROP TABLE announcements;
DROP TABLE user_sessions;
DROP TABLE users;
DROP TABLE asym_signing_keys;
DROP TABLE workspaces;
DROP TABLE groups;