// Code generated by mockery v2.53.0. DO NOT EDIT.

package provider

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockRegistryProtocol is an autogenerated mock type for the RegistryProtocol type
type MockRegistryProtocol struct {
	mock.Mock
}

// DownloadPackage provides a mock function with given fields: ctx, downloadURL
func (_m *MockRegistryProtocol) DownloadPackage(ctx context.Context, downloadURL string) (io.ReadCloser, int64, error) {
	ret := _m.Called(ctx, downloadURL)

	if len(ret) == 0 {
		panic("no return value specified for DownloadPackage")
	}

	var r0 io.ReadCloser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, int64, error)); ok {
		return rf(ctx, downloadURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, downloadURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, downloadURL)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, downloadURL)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetChecksums provides a mock function with given fields: ctx, packageInfo
func (_m *MockRegistryProtocol) GetChecksums(ctx context.Context, packageInfo *PackageInfo) (Checksums, error) {
	ret := _m.Called(ctx, packageInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetChecksums")
	}

	var r0 Checksums
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *PackageInfo) (Checksums, error)); ok {
		return rf(ctx, packageInfo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *PackageInfo) Checksums); ok {
		r0 = rf(ctx, packageInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Checksums)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *PackageInfo) error); ok {
		r1 = rf(ctx, packageInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackageInfo provides a mock function with given fields: ctx, provider, version, os, arch, opts
func (_m *MockRegistryProtocol) GetPackageInfo(ctx context.Context, provider *Provider, version string, os string, arch string, opts ...RequestOption) (*PackageInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, provider, version, os, arch)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageInfo")
	}

	var r0 *PackageInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *Provider, string, string, string, ...RequestOption) (*PackageInfo, error)); ok {
		return rf(ctx, provider, version, os, arch, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Provider, string, string, string, ...RequestOption) *PackageInfo); ok {
		r0 = rf(ctx, provider, version, os, arch, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PackageInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Provider, string, string, string, ...RequestOption) error); ok {
		r1 = rf(ctx, provider, version, os, arch, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVersions provides a mock function with given fields: ctx, provider, opts
func (_m *MockRegistryProtocol) ListVersions(ctx context.Context, provider *Provider, opts ...RequestOption) ([]VersionInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, provider)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []VersionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *Provider, ...RequestOption) ([]VersionInfo, error)); ok {
		return rf(ctx, provider, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Provider, ...RequestOption) []VersionInfo); ok {
		r0 = rf(ctx, provider, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]VersionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Provider, ...RequestOption) error); ok {
		r1 = rf(ctx, provider, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRegistryProtocol creates a new instance of MockRegistryProtocol. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryProtocol(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryProtocol {
	mock := &MockRegistryProtocol{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
