// Code generated by mockery v2.53.0. DO NOT EDIT.

package provider

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceDiscoverer is an autogenerated mock type for the ServiceDiscoverer type
type MockServiceDiscoverer struct {
	mock.Mock
}

// DiscoverTFEServices provides a mock function with given fields: ctx, endpoint
func (_m *MockServiceDiscoverer) DiscoverTFEServices(ctx context.Context, endpoint string) (*TFEServices, error) {
	ret := _m.Called(ctx, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverTFEServices")
	}

	var r0 *TFEServices
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*TFEServices, error)); ok {
		return rf(ctx, endpoint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *TFEServices); ok {
		r0 = rf(ctx, endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TFEServices)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockServiceDiscoverer creates a new instance of MockServiceDiscoverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceDiscoverer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceDiscoverer {
	mock := &MockServiceDiscoverer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
