// Code generated by mockery v2.14.0. DO NOT EDIT.

package activityevent

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/db"

	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// CreateActivityEvent provides a mock function with given fields: ctx, input
func (_m *MockService) CreateActivityEvent(ctx context.Context, input *CreateActivityEventInput) (*models.ActivityEvent, error) {
	ret := _m.Called(ctx, input)

	var r0 *models.ActivityEvent
	if rf, ok := ret.Get(0).(func(context.Context, *CreateActivityEventInput) *models.ActivityEvent); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ActivityEvent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *CreateActivityEventInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActivityEvents provides a mock function with given fields: ctx, input
func (_m *MockService) GetActivityEvents(ctx context.Context, input *GetActivityEventsInput) (*db.ActivityEventsResult, error) {
	ret := _m.Called(ctx, input)

	var r0 *db.ActivityEventsResult
	if rf, ok := ret.Get(0).(func(context.Context, *GetActivityEventsInput) *db.ActivityEventsResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.ActivityEventsResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GetActivityEventsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t mockConstructorTestingTNewMockService) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
