// Code generated by mockery v2.20.0. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	permissions "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/auth/permissions"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockAuthorizer is an autogenerated mock type for the Authorizer type
type MockAuthorizer struct {
	mock.Mock
}

// GetRootNamespaces provides a mock function with given fields: ctx
func (_m *MockAuthorizer) GetRootNamespaces(ctx context.Context) ([]models.MembershipNamespace, error) {
	ret := _m.Called(ctx)

	var r0 []models.MembershipNamespace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.MembershipNamespace, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.MembershipNamespace); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MembershipNamespace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequireAccess provides a mock function with given fields: ctx, perms, checks
func (_m *MockAuthorizer) RequireAccess(ctx context.Context, perms []permissions.Permission, checks ...func(*constraints)) error {
	_va := make([]interface{}, len(checks))
	for _i := range checks {
		_va[_i] = checks[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, perms)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []permissions.Permission, ...func(*constraints)) error); ok {
		r0 = rf(ctx, perms, checks...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequireAccessToInheritableResource provides a mock function with given fields: ctx, resourceTypes, checks
func (_m *MockAuthorizer) RequireAccessToInheritableResource(ctx context.Context, resourceTypes []permissions.ResourceType, checks ...func(*constraints)) error {
	_va := make([]interface{}, len(checks))
	for _i := range checks {
		_va[_i] = checks[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, resourceTypes)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []permissions.ResourceType, ...func(*constraints)) error); ok {
		r0 = rf(ctx, resourceTypes, checks...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockAuthorizer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAuthorizer creates a new instance of MockAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAuthorizer(t mockConstructorTestingTNewMockAuthorizer) *MockAuthorizer {
	mock := &MockAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
