// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockEmailOutboxItems is an autogenerated mock type for the EmailOutboxItems type
type MockEmailOutboxItems struct {
	mock.Mock
}

// ClaimOutboxItems provides a mock function with given fields: ctx, input
func (_m *MockEmailOutboxItems) ClaimOutboxItems(ctx context.Context, input *ClaimOutboxItemsInput) ([]*models.EmailOutboxItem, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ClaimOutboxItems")
	}

	var r0 []*models.EmailOutboxItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ClaimOutboxItemsInput) ([]*models.EmailOutboxItem, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ClaimOutboxItemsInput) []*models.EmailOutboxItem); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.EmailOutboxItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ClaimOutboxItemsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOutboxItem provides a mock function with given fields: ctx, outbox
func (_m *MockEmailOutboxItems) CreateOutboxItem(ctx context.Context, outbox *models.EmailOutboxItem) (*models.EmailOutboxItem, error) {
	ret := _m.Called(ctx, outbox)

	if len(ret) == 0 {
		panic("no return value specified for CreateOutboxItem")
	}

	var r0 *models.EmailOutboxItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.EmailOutboxItem) (*models.EmailOutboxItem, error)); ok {
		return rf(ctx, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.EmailOutboxItem) *models.EmailOutboxItem); ok {
		r0 = rf(ctx, outbox)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailOutboxItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.EmailOutboxItem) error); ok {
		r1 = rf(ctx, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOutboxItems provides a mock function with given fields: ctx, ids
func (_m *MockEmailOutboxItems) DeleteOutboxItems(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOutboxItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOutboxItemByID provides a mock function with given fields: ctx, id
func (_m *MockEmailOutboxItems) GetOutboxItemByID(ctx context.Context, id string) (*models.EmailOutboxItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOutboxItemByID")
	}

	var r0 *models.EmailOutboxItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EmailOutboxItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EmailOutboxItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailOutboxItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOutboxItemByTRN provides a mock function with given fields: ctx, trnValue
func (_m *MockEmailOutboxItems) GetOutboxItemByTRN(ctx context.Context, trnValue string) (*models.EmailOutboxItem, error) {
	ret := _m.Called(ctx, trnValue)

	if len(ret) == 0 {
		panic("no return value specified for GetOutboxItemByTRN")
	}

	var r0 *models.EmailOutboxItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EmailOutboxItem, error)); ok {
		return rf(ctx, trnValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EmailOutboxItem); ok {
		r0 = rf(ctx, trnValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailOutboxItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trnValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOutboxItems provides a mock function with given fields: ctx, input
func (_m *MockEmailOutboxItems) GetOutboxItems(ctx context.Context, input *GetEmailOutboxItemsInput) (*EmailOutboxItemsResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetOutboxItems")
	}

	var r0 *EmailOutboxItemsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetEmailOutboxItemsInput) (*EmailOutboxItemsResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetEmailOutboxItemsInput) *EmailOutboxItemsResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EmailOutboxItemsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetEmailOutboxItemsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOutboxItem provides a mock function with given fields: ctx, item
func (_m *MockEmailOutboxItems) UpdateOutboxItem(ctx context.Context, item *models.EmailOutboxItem) (*models.EmailOutboxItem, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOutboxItem")
	}

	var r0 *models.EmailOutboxItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.EmailOutboxItem) (*models.EmailOutboxItem, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.EmailOutboxItem) *models.EmailOutboxItem); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailOutboxItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.EmailOutboxItem) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEmailOutboxItems creates a new instance of MockEmailOutboxItems. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailOutboxItems(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailOutboxItems {
	mock := &MockEmailOutboxItems{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
