// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWorkItemsQueue is an autogenerated mock type for the WorkItemsQueue type
type MockWorkItemsQueue struct {
	mock.Mock
}

// AcknowledgeWorkItem provides a mock function with given fields: ctx, workItemID
func (_m *MockWorkItemsQueue) AcknowledgeWorkItem(ctx context.Context, workItemID string) error {
	ret := _m.Called(ctx, workItemID)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeWorkItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, workItemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWorkItemToQueue provides a mock function with given fields: ctx, item
func (_m *MockWorkItemsQueue) AddWorkItemToQueue(ctx context.Context, item *AddWorkItemToQueueInput) (*WorkItem, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkItemToQueue")
	}

	var r0 *WorkItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *AddWorkItemToQueueInput) (*WorkItem, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *AddWorkItemToQueueInput) *WorkItem); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WorkItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *AddWorkItemToQueueInput) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimWorkItems provides a mock function with given fields: ctx, input
func (_m *MockWorkItemsQueue) ClaimWorkItems(ctx context.Context, input *ClaimWorkItemsInput) ([]WorkItem, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ClaimWorkItems")
	}

	var r0 []WorkItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ClaimWorkItemsInput) ([]WorkItem, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ClaimWorkItemsInput) []WorkItem); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WorkItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ClaimWorkItemsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockWorkItemsQueue creates a new instance of MockWorkItemsQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkItemsQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkItemsQueue {
	mock := &MockWorkItemsQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
