// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockGroups is an autogenerated mock type for the Groups type
type MockGroups struct {
	mock.Mock
}

// CreateGroup provides a mock function with given fields: ctx, group
func (_m *MockGroups) CreateGroup(ctx context.Context, group *models.Group) (*models.Group, error) {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *models.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) (*models.Group, error)); ok {
		return rf(ctx, group)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) *models.Group); ok {
		r0 = rf(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Group) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGroup provides a mock function with given fields: ctx, group
func (_m *MockGroups) DeleteGroup(ctx context.Context, group *models.Group) error {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) error); ok {
		r0 = rf(ctx, group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChildDepth provides a mock function with given fields: ctx, group
func (_m *MockGroups) GetChildDepth(ctx context.Context, group *models.Group) (int, error) {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for GetChildDepth")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) (int, error)); ok {
		return rf(ctx, group)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) int); ok {
		r0 = rf(ctx, group)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Group) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupByID provides a mock function with given fields: ctx, id
func (_m *MockGroups) GetGroupByID(ctx context.Context, id string) (*models.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByID")
	}

	var r0 *models.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Group); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupByTRN provides a mock function with given fields: ctx, trn
func (_m *MockGroups) GetGroupByTRN(ctx context.Context, trn string) (*models.Group, error) {
	ret := _m.Called(ctx, trn)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByTRN")
	}

	var r0 *models.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Group, error)); ok {
		return rf(ctx, trn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Group); ok {
		r0 = rf(ctx, trn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroups provides a mock function with given fields: ctx, input
func (_m *MockGroups) GetGroups(ctx context.Context, input *GetGroupsInput) (*GroupsResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 *GroupsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetGroupsInput) (*GroupsResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetGroupsInput) *GroupsResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GroupsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetGroupsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrateGroup provides a mock function with given fields: ctx, group, newParentGroup
func (_m *MockGroups) MigrateGroup(ctx context.Context, group *models.Group, newParentGroup *models.Group) (*models.Group, error) {
	ret := _m.Called(ctx, group, newParentGroup)

	if len(ret) == 0 {
		panic("no return value specified for MigrateGroup")
	}

	var r0 *models.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group, *models.Group) (*models.Group, error)); ok {
		return rf(ctx, group, newParentGroup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group, *models.Group) *models.Group); ok {
		r0 = rf(ctx, group, newParentGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Group, *models.Group) error); ok {
		r1 = rf(ctx, group, newParentGroup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateGroup provides a mock function with given fields: ctx, group
func (_m *MockGroups) UpdateGroup(ctx context.Context, group *models.Group) (*models.Group, error) {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 *models.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) (*models.Group, error)); ok {
		return rf(ctx, group)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) *models.Group); ok {
		r0 = rf(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Group) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGroups creates a new instance of MockGroups. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroups(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroups {
	mock := &MockGroups{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
