// Code generated by mockery v2.20.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockVariableVersions is an autogenerated mock type for the VariableVersions type
type MockVariableVersions struct {
	mock.Mock
}

// GetVariableVersionByID provides a mock function with given fields: ctx, id
func (_m *MockVariableVersions) GetVariableVersionByID(ctx context.Context, id string) (*models.VariableVersion, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.VariableVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.VariableVersion, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.VariableVersion); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VariableVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVariableVersions provides a mock function with given fields: ctx, input
func (_m *MockVariableVersions) GetVariableVersions(ctx context.Context, input *GetVariableVersionsInput) (*VariableVersionResult, error) {
	ret := _m.Called(ctx, input)

	var r0 *VariableVersionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetVariableVersionsInput) (*VariableVersionResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetVariableVersionsInput) *VariableVersionResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VariableVersionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetVariableVersionsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockVariableVersions interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockVariableVersions creates a new instance of MockVariableVersions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockVariableVersions(t mockConstructorTestingTNewMockVariableVersions) *MockVariableVersions {
	mock := &MockVariableVersions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
