// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockPackages is an autogenerated mock type for the Packages type
type MockPackages struct {
	mock.Mock
}

// CreatePackage provides a mock function with given fields: ctx, pkg
func (_m *MockPackages) CreatePackage(ctx context.Context, pkg *models.Package) (*models.Package, error) {
	ret := _m.Called(ctx, pkg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePackage")
	}

	var r0 *models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Package) (*models.Package, error)); ok {
		return rf(ctx, pkg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Package) *models.Package); ok {
		r0 = rf(ctx, pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Package) error); ok {
		r1 = rf(ctx, pkg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePackage provides a mock function with given fields: ctx, pkg
func (_m *MockPackages) DeletePackage(ctx context.Context, pkg *models.Package) error {
	ret := _m.Called(ctx, pkg)

	if len(ret) == 0 {
		panic("no return value specified for DeletePackage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Package) error); ok {
		r0 = rf(ctx, pkg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPackageByID provides a mock function with given fields: ctx, id
func (_m *MockPackages) GetPackageByID(ctx context.Context, id string) (*models.Package, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageByID")
	}

	var r0 *models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Package, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Package); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackageByTRN provides a mock function with given fields: ctx, trnValue
func (_m *MockPackages) GetPackageByTRN(ctx context.Context, trnValue string) (*models.Package, error) {
	ret := _m.Called(ctx, trnValue)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageByTRN")
	}

	var r0 *models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Package, error)); ok {
		return rf(ctx, trnValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Package); ok {
		r0 = rf(ctx, trnValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trnValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackages provides a mock function with given fields: ctx, input
func (_m *MockPackages) GetPackages(ctx context.Context, input *GetPackagesInput) (*PackagesResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPackages")
	}

	var r0 *PackagesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetPackagesInput) (*PackagesResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetPackagesInput) *PackagesResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PackagesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetPackagesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePackage provides a mock function with given fields: ctx, pkg
func (_m *MockPackages) UpdatePackage(ctx context.Context, pkg *models.Package) (*models.Package, error) {
	ret := _m.Called(ctx, pkg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePackage")
	}

	var r0 *models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Package) (*models.Package, error)); ok {
		return rf(ctx, pkg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Package) *models.Package); ok {
		r0 = rf(ctx, pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Package) error); ok {
		r1 = rf(ctx, pkg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPackages creates a new instance of MockPackages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackages(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackages {
	mock := &MockPackages{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
