// Code generated by mockery v2.14.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockJobs is an autogenerated mock type for the Jobs type
type MockJobs struct {
	mock.Mock
}

// CreateJob provides a mock function with given fields: ctx, job
func (_m *MockJobs) CreateJob(ctx context.Context, job *models.Job) (*models.Job, error) {
	ret := _m.Called(ctx, job)

	var r0 *models.Job
	if rf, ok := ret.Get(0).(func(context.Context, *models.Job) *models.Job); ok {
		r0 = rf(ctx, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Job) error); ok {
		r1 = rf(ctx, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateJobLogDescriptor provides a mock function with given fields: ctx, descriptor
func (_m *MockJobs) CreateJobLogDescriptor(ctx context.Context, descriptor *models.JobLogDescriptor) (*models.JobLogDescriptor, error) {
	ret := _m.Called(ctx, descriptor)

	var r0 *models.JobLogDescriptor
	if rf, ok := ret.Get(0).(func(context.Context, *models.JobLogDescriptor) *models.JobLogDescriptor); ok {
		r0 = rf(ctx, descriptor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobLogDescriptor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.JobLogDescriptor) error); ok {
		r1 = rf(ctx, descriptor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobByID provides a mock function with given fields: ctx, id
func (_m *MockJobs) GetJobByID(ctx context.Context, id string) (*models.Job, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Job
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Job); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobCountForRunner provides a mock function with given fields: ctx, runnerID
func (_m *MockJobs) GetJobCountForRunner(ctx context.Context, runnerID string) (int, error) {
	ret := _m.Called(ctx, runnerID)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, runnerID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, runnerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobLogDescriptor provides a mock function with given fields: ctx, id
func (_m *MockJobs) GetJobLogDescriptor(ctx context.Context, id string) (*models.JobLogDescriptor, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.JobLogDescriptor
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.JobLogDescriptor); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobLogDescriptor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobLogDescriptorByJobID provides a mock function with given fields: ctx, jobID
func (_m *MockJobs) GetJobLogDescriptorByJobID(ctx context.Context, jobID string) (*models.JobLogDescriptor, error) {
	ret := _m.Called(ctx, jobID)

	var r0 *models.JobLogDescriptor
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.JobLogDescriptor); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobLogDescriptor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobs provides a mock function with given fields: ctx, input
func (_m *MockJobs) GetJobs(ctx context.Context, input *GetJobsInput) (*JobsResult, error) {
	ret := _m.Called(ctx, input)

	var r0 *JobsResult
	if rf, ok := ret.Get(0).(func(context.Context, *GetJobsInput) *JobsResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*JobsResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GetJobsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestJobByType provides a mock function with given fields: ctx, runID, jobType
func (_m *MockJobs) GetLatestJobByType(ctx context.Context, runID string, jobType models.JobType) (*models.Job, error) {
	ret := _m.Called(ctx, runID, jobType)

	var r0 *models.Job
	if rf, ok := ret.Get(0).(func(context.Context, string, models.JobType) *models.Job); ok {
		r0 = rf(ctx, runID, jobType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, models.JobType) error); ok {
		r1 = rf(ctx, runID, jobType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateJob provides a mock function with given fields: ctx, job
func (_m *MockJobs) UpdateJob(ctx context.Context, job *models.Job) (*models.Job, error) {
	ret := _m.Called(ctx, job)

	var r0 *models.Job
	if rf, ok := ret.Get(0).(func(context.Context, *models.Job) *models.Job); ok {
		r0 = rf(ctx, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Job) error); ok {
		r1 = rf(ctx, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateJobLogDescriptor provides a mock function with given fields: ctx, descriptor
func (_m *MockJobs) UpdateJobLogDescriptor(ctx context.Context, descriptor *models.JobLogDescriptor) (*models.JobLogDescriptor, error) {
	ret := _m.Called(ctx, descriptor)

	var r0 *models.JobLogDescriptor
	if rf, ok := ret.Get(0).(func(context.Context, *models.JobLogDescriptor) *models.JobLogDescriptor); ok {
		r0 = rf(ctx, descriptor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobLogDescriptor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.JobLogDescriptor) error); ok {
		r1 = rf(ctx, descriptor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockJobs interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockJobs creates a new instance of MockJobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockJobs(t mockConstructorTestingTNewMockJobs) *MockJobs {
	mock := &MockJobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
