// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockEmailRecipients is an autogenerated mock type for the EmailRecipients type
type MockEmailRecipients struct {
	mock.Mock
}

// AllRecipientsFinal provides a mock function with given fields: ctx, emailOutboxItemID
func (_m *MockEmailRecipients) AllRecipientsFinal(ctx context.Context, emailOutboxItemID string) (bool, error) {
	ret := _m.Called(ctx, emailOutboxItemID)

	if len(ret) == 0 {
		panic("no return value specified for AllRecipientsFinal")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, emailOutboxItemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, emailOutboxItemID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, emailOutboxItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimRecipients provides a mock function with given fields: ctx, input
func (_m *MockEmailRecipients) ClaimRecipients(ctx context.Context, input *ClaimRecipientsInput) ([]*models.EmailRecipient, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ClaimRecipients")
	}

	var r0 []*models.EmailRecipient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ClaimRecipientsInput) ([]*models.EmailRecipient, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ClaimRecipientsInput) []*models.EmailRecipient); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.EmailRecipient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ClaimRecipientsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRecipients provides a mock function with given fields: ctx, recipients
func (_m *MockEmailRecipients) CreateRecipients(ctx context.Context, recipients []*models.EmailRecipient) error {
	ret := _m.Called(ctx, recipients)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipients")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.EmailRecipient) error); ok {
		r0 = rf(ctx, recipients)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRecipientByID provides a mock function with given fields: ctx, id
func (_m *MockEmailRecipients) GetRecipientByID(ctx context.Context, id string) (*models.EmailRecipient, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipientByID")
	}

	var r0 *models.EmailRecipient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EmailRecipient, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EmailRecipient); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailRecipient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipientByTRN provides a mock function with given fields: ctx, trnValue
func (_m *MockEmailRecipients) GetRecipientByTRN(ctx context.Context, trnValue string) (*models.EmailRecipient, error) {
	ret := _m.Called(ctx, trnValue)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipientByTRN")
	}

	var r0 *models.EmailRecipient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EmailRecipient, error)); ok {
		return rf(ctx, trnValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EmailRecipient); ok {
		r0 = rf(ctx, trnValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailRecipient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trnValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipientStats provides a mock function with given fields: ctx, emailOutboxItemID
func (_m *MockEmailRecipients) GetRecipientStats(ctx context.Context, emailOutboxItemID string) (*EmailRecipientStatsResult, error) {
	ret := _m.Called(ctx, emailOutboxItemID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipientStats")
	}

	var r0 *EmailRecipientStatsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*EmailRecipientStatsResult, error)); ok {
		return rf(ctx, emailOutboxItemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *EmailRecipientStatsResult); ok {
		r0 = rf(ctx, emailOutboxItemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EmailRecipientStatsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, emailOutboxItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipients provides a mock function with given fields: ctx, input
func (_m *MockEmailRecipients) GetRecipients(ctx context.Context, input *GetEmailRecipientsInput) (*EmailRecipientsResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipients")
	}

	var r0 *EmailRecipientsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetEmailRecipientsInput) (*EmailRecipientsResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetEmailRecipientsInput) *EmailRecipientsResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EmailRecipientsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetEmailRecipientsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecipient provides a mock function with given fields: ctx, recipient
func (_m *MockEmailRecipients) UpdateRecipient(ctx context.Context, recipient *models.EmailRecipient) (*models.EmailRecipient, error) {
	ret := _m.Called(ctx, recipient)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipient")
	}

	var r0 *models.EmailRecipient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.EmailRecipient) (*models.EmailRecipient, error)); ok {
		return rf(ctx, recipient)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.EmailRecipient) *models.EmailRecipient); ok {
		r0 = rf(ctx, recipient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailRecipient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.EmailRecipient) error); ok {
		r1 = rf(ctx, recipient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEmailRecipients creates a new instance of MockEmailRecipients. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailRecipients(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailRecipients {
	mock := &MockEmailRecipients{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
