// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockNamespaceFavorites is an autogenerated mock type for the NamespaceFavorites type
type MockNamespaceFavorites struct {
	mock.Mock
}

// CreateNamespaceFavorite provides a mock function with given fields: ctx, favorite
func (_m *MockNamespaceFavorites) CreateNamespaceFavorite(ctx context.Context, favorite *models.NamespaceFavorite) (*models.NamespaceFavorite, error) {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for CreateNamespaceFavorite")
	}

	var r0 *models.NamespaceFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.NamespaceFavorite) (*models.NamespaceFavorite, error)); ok {
		return rf(ctx, favorite)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.NamespaceFavorite) *models.NamespaceFavorite); ok {
		r0 = rf(ctx, favorite)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NamespaceFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.NamespaceFavorite) error); ok {
		r1 = rf(ctx, favorite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNamespaceFavorite provides a mock function with given fields: ctx, favorite
func (_m *MockNamespaceFavorites) DeleteNamespaceFavorite(ctx context.Context, favorite *models.NamespaceFavorite) error {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespaceFavorite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.NamespaceFavorite) error); ok {
		r0 = rf(ctx, favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNamespaceFavoriteByID provides a mock function with given fields: ctx, id
func (_m *MockNamespaceFavorites) GetNamespaceFavoriteByID(ctx context.Context, id string) (*models.NamespaceFavorite, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceFavoriteByID")
	}

	var r0 *models.NamespaceFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.NamespaceFavorite, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.NamespaceFavorite); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NamespaceFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNamespaceFavoriteByTRN provides a mock function with given fields: ctx, trn
func (_m *MockNamespaceFavorites) GetNamespaceFavoriteByTRN(ctx context.Context, trn string) (*models.NamespaceFavorite, error) {
	ret := _m.Called(ctx, trn)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceFavoriteByTRN")
	}

	var r0 *models.NamespaceFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.NamespaceFavorite, error)); ok {
		return rf(ctx, trn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.NamespaceFavorite); ok {
		r0 = rf(ctx, trn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NamespaceFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNamespaceFavorites provides a mock function with given fields: ctx, input
func (_m *MockNamespaceFavorites) GetNamespaceFavorites(ctx context.Context, input *GetNamespaceFavoritesInput) (*NamespaceFavoritesResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceFavorites")
	}

	var r0 *NamespaceFavoritesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetNamespaceFavoritesInput) (*NamespaceFavoritesResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetNamespaceFavoritesInput) *NamespaceFavoritesResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NamespaceFavoritesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetNamespaceFavoritesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockNamespaceFavorites creates a new instance of MockNamespaceFavorites. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamespaceFavorites(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamespaceFavorites {
	mock := &MockNamespaceFavorites{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
