// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockAgentSessionMessages is an autogenerated mock type for the AgentSessionMessages type
type MockAgentSessionMessages struct {
	mock.Mock
}

// CreateAgentSessionMessage provides a mock function with given fields: ctx, msg
func (_m *MockAgentSessionMessages) CreateAgentSessionMessage(ctx context.Context, msg *models.AgentSessionMessage) (*models.AgentSessionMessage, error) {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgentSessionMessage")
	}

	var r0 *models.AgentSessionMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AgentSessionMessage) (*models.AgentSessionMessage, error)); ok {
		return rf(ctx, msg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.AgentSessionMessage) *models.AgentSessionMessage); ok {
		r0 = rf(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AgentSessionMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.AgentSessionMessage) error); ok {
		r1 = rf(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAgentSessionMessageByID provides a mock function with given fields: ctx, sessionID, id
func (_m *MockAgentSessionMessages) GetAgentSessionMessageByID(ctx context.Context, sessionID string, id string) (*models.AgentSessionMessage, error) {
	ret := _m.Called(ctx, sessionID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentSessionMessageByID")
	}

	var r0 *models.AgentSessionMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.AgentSessionMessage, error)); ok {
		return rf(ctx, sessionID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.AgentSessionMessage); ok {
		r0 = rf(ctx, sessionID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AgentSessionMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sessionID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAgentSessionMessages provides a mock function with given fields: ctx, input
func (_m *MockAgentSessionMessages) GetAgentSessionMessages(ctx context.Context, input *GetAgentSessionMessagesInput) (*AgentSessionMessagesResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentSessionMessages")
	}

	var r0 *AgentSessionMessagesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetAgentSessionMessagesInput) (*AgentSessionMessagesResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetAgentSessionMessagesInput) *AgentSessionMessagesResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AgentSessionMessagesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetAgentSessionMessagesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAgentSessionMessages creates a new instance of MockAgentSessionMessages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentSessionMessages(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentSessionMessages {
	mock := &MockAgentSessionMessages{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
