// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockPolicies is an autogenerated mock type for the Policies type
type MockPolicies struct {
	mock.Mock
}

// CreatePolicy provides a mock function with given fields: ctx, policy
func (_m *MockPolicies) CreatePolicy(ctx context.Context, policy *models.Policy) (*models.Policy, error) {
	ret := _m.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for CreatePolicy")
	}

	var r0 *models.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Policy) (*models.Policy, error)); ok {
		return rf(ctx, policy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Policy) *models.Policy); ok {
		r0 = rf(ctx, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Policy) error); ok {
		r1 = rf(ctx, policy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePolicy provides a mock function with given fields: ctx, policy
func (_m *MockPolicies) DeletePolicy(ctx context.Context, policy *models.Policy) error {
	ret := _m.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Policy) error); ok {
		r0 = rf(ctx, policy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPolicies provides a mock function with given fields: ctx, input
func (_m *MockPolicies) GetPolicies(ctx context.Context, input *GetPoliciesInput) (*PoliciesResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicies")
	}

	var r0 *PoliciesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetPoliciesInput) (*PoliciesResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetPoliciesInput) *PoliciesResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PoliciesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetPoliciesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicyByID provides a mock function with given fields: ctx, id
func (_m *MockPolicies) GetPolicyByID(ctx context.Context, id string) (*models.Policy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyByID")
	}

	var r0 *models.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Policy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Policy); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicyByTRN provides a mock function with given fields: ctx, trnValue
func (_m *MockPolicies) GetPolicyByTRN(ctx context.Context, trnValue string) (*models.Policy, error) {
	ret := _m.Called(ctx, trnValue)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyByTRN")
	}

	var r0 *models.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Policy, error)); ok {
		return rf(ctx, trnValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Policy); ok {
		r0 = rf(ctx, trnValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trnValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePolicy provides a mock function with given fields: ctx, policy
func (_m *MockPolicies) UpdatePolicy(ctx context.Context, policy *models.Policy) (*models.Policy, error) {
	ret := _m.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 *models.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Policy) (*models.Policy, error)); ok {
		return rf(ctx, policy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Policy) *models.Policy); ok {
		r0 = rf(ctx, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Policy) error); ok {
		r1 = rf(ctx, policy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPolicies creates a new instance of MockPolicies. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicies(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicies {
	mock := &MockPolicies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
