// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockRunGateApprovals is an autogenerated mock type for the RunGateApprovals type
type MockRunGateApprovals struct {
	mock.Mock
}

// CreateRunGateApproval provides a mock function with given fields: ctx, approval
func (_m *MockRunGateApprovals) CreateRunGateApproval(ctx context.Context, approval *models.RunGateApproval) (*models.RunGateApproval, error) {
	ret := _m.Called(ctx, approval)

	if len(ret) == 0 {
		panic("no return value specified for CreateRunGateApproval")
	}

	var r0 *models.RunGateApproval
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RunGateApproval) (*models.RunGateApproval, error)); ok {
		return rf(ctx, approval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.RunGateApproval) *models.RunGateApproval); ok {
		r0 = rf(ctx, approval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RunGateApproval)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.RunGateApproval) error); ok {
		r1 = rf(ctx, approval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunGateApprovalByID provides a mock function with given fields: ctx, id
func (_m *MockRunGateApprovals) GetRunGateApprovalByID(ctx context.Context, id string) (*models.RunGateApproval, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRunGateApprovalByID")
	}

	var r0 *models.RunGateApproval
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RunGateApproval, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RunGateApproval); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RunGateApproval)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunGateApprovalByTRN provides a mock function with given fields: ctx, trnValue
func (_m *MockRunGateApprovals) GetRunGateApprovalByTRN(ctx context.Context, trnValue string) (*models.RunGateApproval, error) {
	ret := _m.Called(ctx, trnValue)

	if len(ret) == 0 {
		panic("no return value specified for GetRunGateApprovalByTRN")
	}

	var r0 *models.RunGateApproval
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RunGateApproval, error)); ok {
		return rf(ctx, trnValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RunGateApproval); ok {
		r0 = rf(ctx, trnValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RunGateApproval)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trnValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunGateApprovalsByGateID provides a mock function with given fields: ctx, gateID
func (_m *MockRunGateApprovals) GetRunGateApprovalsByGateID(ctx context.Context, gateID string) ([]models.RunGateApproval, error) {
	ret := _m.Called(ctx, gateID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunGateApprovalsByGateID")
	}

	var r0 []models.RunGateApproval
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.RunGateApproval, error)); ok {
		return rf(ctx, gateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.RunGateApproval); ok {
		r0 = rf(ctx, gateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RunGateApproval)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, gateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRunGateApproval provides a mock function with given fields: ctx, approval
func (_m *MockRunGateApprovals) UpdateRunGateApproval(ctx context.Context, approval *models.RunGateApproval) (*models.RunGateApproval, error) {
	ret := _m.Called(ctx, approval)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunGateApproval")
	}

	var r0 *models.RunGateApproval
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RunGateApproval) (*models.RunGateApproval, error)); ok {
		return rf(ctx, approval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.RunGateApproval) *models.RunGateApproval); ok {
		r0 = rf(ctx, approval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RunGateApproval)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.RunGateApproval) error); ok {
		r1 = rf(ctx, approval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRunGateApprovals creates a new instance of MockRunGateApprovals. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunGateApprovals(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunGateApprovals {
	mock := &MockRunGateApprovals{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
