// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockLogStreamChunks is an autogenerated mock type for the LogStreamChunks type
type MockLogStreamChunks struct {
	mock.Mock
}

// CreateLogStreamChunk provides a mock function with given fields: ctx, chunk
func (_m *MockLogStreamChunks) CreateLogStreamChunk(ctx context.Context, chunk *models.LogStreamChunk) (*models.LogStreamChunk, error) {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogStreamChunk")
	}

	var r0 *models.LogStreamChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LogStreamChunk) (*models.LogStreamChunk, error)); ok {
		return rf(ctx, chunk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.LogStreamChunk) *models.LogStreamChunk); ok {
		r0 = rf(ctx, chunk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LogStreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.LogStreamChunk) error); ok {
		r1 = rf(ctx, chunk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveChunk provides a mock function with given fields: ctx, logStreamID
func (_m *MockLogStreamChunks) GetActiveChunk(ctx context.Context, logStreamID string) (*models.LogStreamChunk, error) {
	ret := _m.Called(ctx, logStreamID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveChunk")
	}

	var r0 *models.LogStreamChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.LogStreamChunk, error)); ok {
		return rf(ctx, logStreamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.LogStreamChunk); ok {
		r0 = rf(ctx, logStreamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LogStreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, logStreamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOverlappingChunks provides a mock function with given fields: ctx, logStreamID, startOffset, endOffset
func (_m *MockLogStreamChunks) GetOverlappingChunks(ctx context.Context, logStreamID string, startOffset int, endOffset int) ([]models.LogStreamChunk, error) {
	ret := _m.Called(ctx, logStreamID, startOffset, endOffset)

	if len(ret) == 0 {
		panic("no return value specified for GetOverlappingChunks")
	}

	var r0 []models.LogStreamChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.LogStreamChunk, error)); ok {
		return rf(ctx, logStreamID, startOffset, endOffset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.LogStreamChunk); ok {
		r0 = rf(ctx, logStreamID, startOffset, endOffset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LogStreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, logStreamID, startOffset, endOffset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLogStreamChunk provides a mock function with given fields: ctx, chunk
func (_m *MockLogStreamChunks) UpdateLogStreamChunk(ctx context.Context, chunk *models.LogStreamChunk) (*models.LogStreamChunk, error) {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLogStreamChunk")
	}

	var r0 *models.LogStreamChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LogStreamChunk) (*models.LogStreamChunk, error)); ok {
		return rf(ctx, chunk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.LogStreamChunk) *models.LogStreamChunk); ok {
		r0 = rf(ctx, chunk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LogStreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.LogStreamChunk) error); ok {
		r1 = rf(ctx, chunk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockLogStreamChunks creates a new instance of MockLogStreamChunks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogStreamChunks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogStreamChunks {
	mock := &MockLogStreamChunks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
