// Code generated by mockery v2.53.0. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockPackageVersions is an autogenerated mock type for the PackageVersions type
type MockPackageVersions struct {
	mock.Mock
}

// CreatePackageVersion provides a mock function with given fields: ctx, packageVersion
func (_m *MockPackageVersions) CreatePackageVersion(ctx context.Context, packageVersion *models.PackageVersion) (*models.PackageVersion, error) {
	ret := _m.Called(ctx, packageVersion)

	if len(ret) == 0 {
		panic("no return value specified for CreatePackageVersion")
	}

	var r0 *models.PackageVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion) (*models.PackageVersion, error)); ok {
		return rf(ctx, packageVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion) *models.PackageVersion); ok {
		r0 = rf(ctx, packageVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PackageVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.PackageVersion) error); ok {
		r1 = rf(ctx, packageVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePackageVersion provides a mock function with given fields: ctx, packageVersion
func (_m *MockPackageVersions) DeletePackageVersion(ctx context.Context, packageVersion *models.PackageVersion) error {
	ret := _m.Called(ctx, packageVersion)

	if len(ret) == 0 {
		panic("no return value specified for DeletePackageVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion) error); ok {
		r0 = rf(ctx, packageVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPackageVersionByID provides a mock function with given fields: ctx, id
func (_m *MockPackageVersions) GetPackageVersionByID(ctx context.Context, id string) (*models.PackageVersion, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageVersionByID")
	}

	var r0 *models.PackageVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PackageVersion, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PackageVersion); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PackageVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackageVersionByTRN provides a mock function with given fields: ctx, trnValue
func (_m *MockPackageVersions) GetPackageVersionByTRN(ctx context.Context, trnValue string) (*models.PackageVersion, error) {
	ret := _m.Called(ctx, trnValue)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageVersionByTRN")
	}

	var r0 *models.PackageVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PackageVersion, error)); ok {
		return rf(ctx, trnValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PackageVersion); ok {
		r0 = rf(ctx, trnValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PackageVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trnValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackageVersions provides a mock function with given fields: ctx, input
func (_m *MockPackageVersions) GetPackageVersions(ctx context.Context, input *GetPackageVersionsInput) (*PackageVersionsResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageVersions")
	}

	var r0 *PackageVersionsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetPackageVersionsInput) (*PackageVersionsResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetPackageVersionsInput) *PackageVersionsResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PackageVersionsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetPackageVersionsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePackageVersion provides a mock function with given fields: ctx, packageVersion
func (_m *MockPackageVersions) UpdatePackageVersion(ctx context.Context, packageVersion *models.PackageVersion) (*models.PackageVersion, error) {
	ret := _m.Called(ctx, packageVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePackageVersion")
	}

	var r0 *models.PackageVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion) (*models.PackageVersion, error)); ok {
		return rf(ctx, packageVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.PackageVersion) *models.PackageVersion); ok {
		r0 = rf(ctx, packageVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PackageVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.PackageVersion) error); ok {
		r1 = rf(ctx, packageVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPackageVersions creates a new instance of MockPackageVersions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageVersions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageVersions {
	mock := &MockPackageVersions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
