// Code generated by mockery v2.53.0. DO NOT EDIT.

package cleanuppolicy

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/internal/models"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// CreateCleanupPolicy provides a mock function with given fields: ctx, input
func (_m *MockService) CreateCleanupPolicy(ctx context.Context, input *CreateCleanupPolicyInput) (*models.CleanupPolicy, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCleanupPolicy")
	}

	var r0 *models.CleanupPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateCleanupPolicyInput) (*models.CleanupPolicy, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateCleanupPolicyInput) *models.CleanupPolicy); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CleanupPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateCleanupPolicyInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCleanupPolicy provides a mock function with given fields: ctx, input
func (_m *MockService) DeleteCleanupPolicy(ctx context.Context, input *DeleteCleanupPolicyInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCleanupPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *DeleteCleanupPolicyInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCleanupPoliciesByIDs provides a mock function with given fields: ctx, ids
func (_m *MockService) GetCleanupPoliciesByIDs(ctx context.Context, ids []string) ([]*models.CleanupPolicy, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetCleanupPoliciesByIDs")
	}

	var r0 []*models.CleanupPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*models.CleanupPolicy, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*models.CleanupPolicy); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CleanupPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCleanupPolicyByID provides a mock function with given fields: ctx, id
func (_m *MockService) GetCleanupPolicyByID(ctx context.Context, id string) (*models.CleanupPolicy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCleanupPolicyByID")
	}

	var r0 *models.CleanupPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.CleanupPolicy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.CleanupPolicy); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CleanupPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCleanupPolicyByTRN provides a mock function with given fields: ctx, trnValue
func (_m *MockService) GetCleanupPolicyByTRN(ctx context.Context, trnValue string) (*models.CleanupPolicy, error) {
	ret := _m.Called(ctx, trnValue)

	if len(ret) == 0 {
		panic("no return value specified for GetCleanupPolicyByTRN")
	}

	var r0 *models.CleanupPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.CleanupPolicy, error)); ok {
		return rf(ctx, trnValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.CleanupPolicy); ok {
		r0 = rf(ctx, trnValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CleanupPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trnValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEffectiveCleanupPolicies provides a mock function with given fields: ctx, namespacePath
func (_m *MockService) GetEffectiveCleanupPolicies(ctx context.Context, namespacePath string) ([]*models.CleanupPolicy, error) {
	ret := _m.Called(ctx, namespacePath)

	if len(ret) == 0 {
		panic("no return value specified for GetEffectiveCleanupPolicies")
	}

	var r0 []*models.CleanupPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.CleanupPolicy, error)); ok {
		return rf(ctx, namespacePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.CleanupPolicy); ok {
		r0 = rf(ctx, namespacePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CleanupPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespacePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCleanupPolicy provides a mock function with given fields: ctx, input
func (_m *MockService) UpdateCleanupPolicy(ctx context.Context, input *UpdateCleanupPolicyInput) (*models.CleanupPolicy, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCleanupPolicy")
	}

	var r0 *models.CleanupPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *UpdateCleanupPolicyInput) (*models.CleanupPolicy, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *UpdateCleanupPolicyInput) *models.CleanupPolicy); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CleanupPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *UpdateCleanupPolicyInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
